### ISSUE TITLE
FileNotFoundException: translate.conf (No such file or directory)

### ISSUE THREAD

**Issue by vbauer** [takari/maven-polyglot#13]
I've tried last binary version and can't run "translate" task:

```bash
vbauer@vladislav-bauer:~/workspace/java/simba$ /home/vbauer/Applications/tesla-polyglot/bin/translate pom.xml pom.yaml
java.io.FileNotFoundException: /home/vbauer/Applications/apache-maven/bin/translate.conf (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:120)
	at java.io.FileInputStream.<init>(FileInputStream.java:79)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:390)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
vbauer@vladislav-bauer:~/workspace/java/simba$ cd ~/Applications/tesla-polyglot/bin/
vbauer@vladislav-bauer:~/Applications/tesla-polyglot/bin$ ls -la
total 72
drwxrwxrwx 2 vbauer vbauer 4096 Jan 20 08:27 .
drwxrwxrwx 7 vbauer vbauer 4096 Jan 20 08:27 ..
-rw-r--r-- 1 vbauer vbauer  478 Jan 20 08:27 m2.conf
-rwxr-xr-x 1 vbauer vbauer 5807 Jan 20 08:27 mvn
-rwxrwxrwx 1 vbauer vbauer 6150 Sep 30 21:57 mvn.bat
-rwxr-xr-x 1 vbauer vbauer 5955 Jan 20 08:27 mvnDebug
-rwxrwxrwx 1 vbauer vbauer 6304 Sep 30 21:57 mvnDebug.bat
-rwxr-xr-x 1 vbauer vbauer 6114 Jan 20 08:27 mvnyjp
-rwxr-xr-x 1 vbauer vbauer 4382 Jan 20 08:27 translate
-rwxrwxrwx 1 vbauer vbauer 6009 Jan 20 08:27 translate.bat
-rw-r--r-- 1 vbauer vbauer  418 Jan 20 08:27 translate.conf
```

The same problem happens when I run translate task in directory "maven-polyglot/bin"
```bash
vbauer@vladislav-bauer:~/Applications/tesla-polyglot/bin$ ./translate ~/workspace/java/simba/pom.xml pom.yaml
java.io.FileNotFoundException: /home/vbauer/Applications/apache-maven/bin/translate.conf (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:120)
	at java.io.FileInputStream.<init>(FileInputStream.java:79)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:390)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
"translate.conf" is placed in another place, not "/home/vbauer/Applications/apache-maven/bin/translate.conf", but "/home/vbauer/Applications/tesla-polyglot/bin/translate.conf"

**Comment by jvanzyl** [comment]
There is a new translate plugin: http://takari.io/2015/03/21/polyglot-maven.html
